### ISSUE TITLE
RSD Part 2

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/TEAM2018#44]
RSD November Sprint.

@jmaassen will you together with @jspaaks fill in the info about this issue?

**Comment by romulogoncalves** [comment]
@jspaaks  is there project hours for this work? If yes, which one?
jspaaks says: R&D

**Comment by jspaaks** [comment]
- [ ] Set up an instance of the Research Software Directory for PROCESS
- [ ] Set up an instance of the Research Software Directory for Ibis/JungleComputing
    - https://cs.vu.nl/ibis/index.html
- [x] Set up an instance of the Research Software Directory for [CCS Amsterdam](http://ccs.amsterdam/), http://ccs.amsterdam/tools-software/
    - [x] put this http://ccs.amsterdam/publications/ in a new Zotero library. https://www.zotero.org/groups/2256954/ccsamsterdam
    - [x] copy-paste projects data from http://ccs.amsterdam/projects/
    - [x] copy-paste people information from http://ccs.amsterdam/people/ with the Admin interface
- [ ] Set up an instance of the Research Software Directory for AMC
- [ ] Describe how to set up a new instance
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/167
- [ ] Write a manual for engineers how to make a new entry in the Research Software Directory
    - [x] https://github.com/research-software-directory/research-software-directory/issues/143 (bencomp issue about how to add software/person/mention etc)
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/163 (clean up tasks-nlesc readme)
    - [x] https://github.com/research-software-directory/research-software-directory/issues/164 (update zotero file)
- [ ] Merge greenkeeper PRs in rsd/admin
- [x] Add github link to source code (Merge PR)
    - [x] https://github.com/research-software-directory/research-software-directory/issues/102
    - [x] https://github.com/research-software-directory/frontend/pull/87
- [ ] Extend schema: make ``related.mentions.url`` a required property:
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/126
- [ ] Extend schema: ``uniqueItem`` for arrays
- [ ] Admin interface display style for dropdown items
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/118
- [ ] Data model for Zotero: can we get away with having an 'impact' collection and an 'output' collection. Or should we add impact items to the project folders that until now contained "only" output?
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/72
- [ ] url from zotero may be invalid
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/162
- [x] Merge Katrins PR doi.org instead of dx.doi.org
    - [x] https://github.com/research-software-directory/tasks-nlesc/pull/6/files
- [ ] For mentions that are YouTube videos, show a thumbnail
- [ ] Make a status overview SPA, per page and aggregated, both tables and graphs, other forms
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/60 (quickly gain insight)
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/146
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/156
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/159
- [ ] Add FAQ for removing the NLeSC data from the test instance
- [ ] Add FAQ for changing the schema such that you can manually add a Project via the Admin interface like you would add a Person.
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/158
- [ ] Add 'Fork me on GitHub' ribbon
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/160
- [ ] Add FAQ: updating the search properties (edit schema)
- [ ] Add to /create detailed walkthrough 
    - [ ] upload to Amazon instructions 
    - [ ] backup RSD data /MongoDB instructions
    - [ ] backup Zotero instructions
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/167
- [ ] Add FAQ describe how to make changes to the admin interface 
    - [ ] https://github.com/research-software-directory/research-software-directory/issues/171
- [ ] make a template page for projects
- [x] Increase frequency of update tasks
- [ ] Figure out and describe the setup needed to push organization-specific customizations back to GitHub

**Comment by jspaaks** [comment]
- [x] [3d-e-chem-knime-pharmacophore](https://research-software.nl/software/3d-e-chem-knime-pharmacophore)KNIME Pharmacophore
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [3d-e-chem-knime-kripodb](https://research-software.nl/software/knime-kripodb) KNIME node for Kripo
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [3d-e-chem-knime-silicos-it](https://research-software.nl/software/3d-e-chem-knime-pharmacophore)KNIME Silicos-it nodes
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [3d-e-chem-knime-plants](https://research-software.nl/software/3d-e-chem-knime-plants)KNIME PLANTS
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [3d-e-chem-knime-python-wrapper](https://research-software.nl/software/3d-e-chem-knime-python-wrapper)KNIME Python wrapper
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [3d-e-chem-sygma](https://research-software.nl/software/3d-e-chem-sygma)SyGMa
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [3d-e-chem-vm](https://research-software.nl/software/3d-e-chem-vm)3D-e-Chem Virtual Machine
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [ahn-pointcloud-viewer-ws](https://research-software.nl/software/ahn-pointcloud-viewer-ws)AHN point cloud viewer web service
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [ ] [ahn2webviewer](https://research-software.nl/software/ahn2webviewer)AHN2 pointcloud viewer
    - [x] short statement
    - [ ] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [allelic-variation-explorer](https://research-software.nl/software/allelic-variation-explorer)Allelic Variation Explorer
    - [ ] short statement
    - [x] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [ ] [amuse](https://research-software.nl/software/amuse)AMUSE
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [beyond-the-book](https://research-software.nl/software/beyond-the-book)Beyond the book
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [ ] organizations
    - [ ] projects
    - [x] contributors
- [ ] [case-law-app](https://research-software.nl/software/case-law-app)Case Law App
    - [x] short statement
    - [ ] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [caselawanalytics](https://research-software.nl/software/caselawanalytics)caselawnet
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [cesium-ncwms](https://research-software.nl/software/cesium-ncwms)Cesium-ncWMS
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [ ] organizations
    - [ ] projects
    - [x] contributors
- [ ] [chemical-analytics-platform](https://research-software.nl/software/chemical-analytics-platform)Chemical Analytics Platform
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [cptm](https://research-software.nl/software/cptm)Cross-perspective Topic Modeling
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [dive](https://research-software.nl/software/dive)Dive
    - [ ] short statement
    - [x] getting started
    - [ ] citation
    - [ ] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [eecology-annotation](https://research-software.nl/software/eecology-annotation)eEcology Annotation Tool
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [eecology-sms-reciever](https://research-software.nl/software/eecology-sms-reciever)eEcology-SMS-reciever
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [eecology-tracker-calendar](https://research-software.nl/software/eecology-tracker-calendar)eEcology Tracker calendar
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [pyelsepa](https://research-software.nl/software/pyelsepa)PyELSEPA
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [x] [ewaterleaf](https://research-software.nl/software/ewaterleaf)eWaterLeaf
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [fairdatapoint](https://research-software.nl/software/fairdatapoint)FAIR Data Point
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [ ] contributors
- [ ] [fastmlc](https://research-software.nl/software/fastmlc)FastMLC
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [ ] contributors
- [ ] [finding-journalists](https://research-software.nl/software/finding-journalists)Lysander
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [ ] [frbcat-web](https://research-software.nl/software/frbcat-web)frbcat-web
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [frbcatdb](https://research-software.nl/software/frbcatdb)frbcatdb
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [grlc](https://research-software.nl/software/grlc)grlc
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [x] [hadrianus-scripts](https://research-software.nl/software/hadrianus-scripts)Hadrianus scripts
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [hypercanny](https://research-software.nl/software/hypercanny)HyperCanny
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [ ] [kernel-tuner](https://research-software.nl/software/kernel-tuner)Kernel Tuner
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [ ] [knime-gpcrdb](https://research-software.nl/software/knime-gpcrdb)GPCRdb KNIME nodes
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [knime-molviewer](https://research-software.nl/software/knime-molviewer)KNIME molecule viewer nodes
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [knime-sstea](https://research-software.nl/software/knime-sstea)KNIME ss-TEA node
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [knime-testflow](https://research-software.nl/software/knime-testflow)KNIME Testflow
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [linked-data-platform-for-plant-breeding-genomics](https://research-software.nl/software/linked-data-platform-for-plant-breeding-genomics)pbg-ld
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [magma](https://research-software.nl/software/magma)MAGMa
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [massivepotreeconverter](https://research-software.nl/software/massivepotreeconverter)Massive PotreeConverter
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [mcfly](https://research-software.nl/software/mcfly)mcfly
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [ ] contributors
- [ ] [mdstudio](https://research-software.nl/software/mdstudio)MDStudio
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [ ] [mmsoda-toolbox-for-matlab](https://research-software.nl/software/mmsoda-toolbox-for-matlab)MMSODA Toolbox for MATLAB
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [x] [nlppln](https://research-software.nl/software/nlppln)nlppln
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [noodles](https://research-software.nl/software/noodles)Noodles
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [ ] [ochre](https://research-software.nl/software/ochre)ochre
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [octseg](https://research-software.nl/software/octseg)OCTSEG
    - [ ] short statement
    - [ ] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [ ] organizations
    - [ ] projects
    - [x] contributors
- [ ] [omuse](https://research-software.nl/software/omuse)OMUSE
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [online-behaviour-machine-learning](https://research-software.nl/software/online-behaviour-machine-learning)Hercules
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [osmium](https://research-software.nl/software/osmium)Osmium
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [pattyanalytics](https://research-software.nl/software/pattyanalytics)PattyAnalytics
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [pattyvis](https://research-software.nl/software/pattyvis)Via Appia Visualization
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [pidimehs-library](https://research-software.nl/software/pidimehs-library)PIDIMEHS library
    - [ ] short statement
    - [ ] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [python-pcl](https://research-software.nl/software/python-pcl)python-pcl
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [pyxenon](https://research-software.nl/software/pyxenon)PyXenon
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [qmflows](https://research-software.nl/software/qmflows)QMflows
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [qtl-tableminer](https://research-software.nl/software/qtl-tableminer)QTLTableMiner++
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [ ] contributors
- [ ] [recipy](https://research-software.nl/software/recipy)recipy
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [ ] organizations
    - [ ] projects
    - [x] contributors
- [ ] [sagecal](https://research-software.nl/software/sagecal)Sagecal
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [ ] contributors
- [ ] [salient-detector-python](https://research-software.nl/software/salient-detector-python)SalientDetector-python
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [salient-descriptor-matlab](https://research-software.nl/software/salient-descriptor-matlab)SalientDescriptor-matlab
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [salient-detector-matlab](https://research-software.nl/software/salient-detector-matlab)SalientDetector-matlab
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [x] [scriptcwl](https://research-software.nl/software/scriptcwl)scriptcwl
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [structure-from-motion](https://research-software.nl/software/structure-from-motion)Structure from Motion
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [emma](https://research-software.nl/software/emma)Emma
    - [ ] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [x] [shifting-concepts-through-time](https://research-software.nl/software/shifting-concepts-through-time)ShiCo
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [siga-py](https://research-software.nl/software/siga-py)SIGA.py
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [spot](https://research-software.nl/software/spot)SPOT
    - [x] short statement
    - [ ] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [storyteller](https://research-software.nl/software/storyteller)StoryTeller
    - [x] short statement
    - [ ] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [ ] organizations
    - [x] projects
    - [ ] contributors
- [ ] [one-button-compute](https://research-software.nl/software/one-button-compute)One button compute
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [twinl-website-code](https://research-software.nl/software/twinl-website-code)Twiqs
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [x] [ggir](https://research-software.nl/software/ggir)GGIR
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [x] [xenon](https://research-software.nl/software/xenon)Xenon
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [xenon-cli](https://research-software.nl/software/xenon-cli)Xenon command line interface
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [xenon-grpc](https://research-software.nl/software/xenon-grpc)Xenon gRPC server
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [boatswain](https://research-software.nl/software/boatswain)boatswain
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [ ] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [research-software-directory](https://research-software.nl/software/research-software-directory)Research Software Directory
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [xtas](https://research-software.nl/software/xtas)xtas
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [texcavator](https://research-software.nl/software/texcavator)Texcavator
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [cffconvert](https://research-software.nl/software/cffconvert)cffconvert
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [sv-callers](https://research-software.nl/software/sv-callers)sv-callers
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [nlesc-python-template](https://research-software.nl/software/nlesc-python-template)Netherlands eScience Center Python Template
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [ ] organizations
    - [ ] projects
    - [x] contributors
- [ ] [cffinit](https://research-software.nl/software/cffinit)cffinit
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [ ] projects
    - [x] contributors
- [ ] [esmvaltool](https://research-software.nl/software/esmvaltool)ESMValTool
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [jupyterlab-thredds](https://research-software.nl/software/jupyterlab-thredds)JupyterLab dataset browser for THREDDS
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [experiment-launcher](https://research-software.nl/software/experiment-launcher)Experiment Launcher
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [x] [satsense](https://research-software.nl/software/satsense)Satsense
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [yatiml](https://research-software.nl/software/yatiml)yatiml
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [x] organizations
    - [x] projects
    - [x] contributors
- [ ] [cerulean](https://research-software.nl/software/cerulean)cerulean
    - [x] short statement
    - [x] getting started
    - [ ] citation
    - [x] bullets
    - [x] read more
    - [ ] organizations
    - [x] projects
    - [x] contributors
- [ ] [lofar-linked-data-platform](https://research-software.nl/software/lofar-linked-data-platform)lofar-ld
    - [x] short statement
    - [x] getting started
    - [x] citation
    - [x] bullets
    - [ ] read more
    - [x] organizations
    - [x] projects
    - [x] contributors

**Comment by jspaaks** [comment]
- PROCESS: https://ec2-34-221-149-172.us-west-2.compute.amazonaws.com/
- CCS Amsterdam: https://ec2-52-36-66-25.us-west-2.compute.amazonaws.com/

**Comment by jmaassen** [comment]
aggregated quality metric
https://docs.google.com/spreadsheets/d/e/2PACX-1vQYWrg0Taw20qz_TrgbgbUaMYZFQFZWVcxAywOd6OPbW8KfnmBxulbY2WOufvktgebZmVsRuYYQwriS/pubchart?oid=2134606275&format=interactive

issue types:
https://docs.google.com/spreadsheets/d/e/2PACX-1vQYWrg0Taw20qz_TrgbgbUaMYZFQFZWVcxAywOd6OPbW8KfnmBxulbY2WOufvktgebZmVsRuYYQwriS/pubchart?oid=1573053544&format=interactive

**Comment by romulogoncalves** [comment]
@jmaassen @jspaaks what can the TechLeads do here to make sure things are moving forward?

**Comment by jmaassen** [comment]
This is all being worked on in the RSD development which I'm managing. Lets close this issue.
